id: I568A6109
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:00.540379
last_modified: 2023-01-04 11:30:00.540400
source_metadata:
  collections:
  - Böpa Tulku Dongak Tenpe Nyima
  - Works of Tibetan Masters
bases:
  B491:
    title: Biography of Böpa Tulku Dongak Tenpé Nyima
    base_file: B491.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
